# Generated by Django 5.1 on 2025-11-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(max_length=50)),
                ('duracion_minutos', models.IntegerField()),
                ('cupo_maximo', models.IntegerField()),
                ('nivel_dificultad', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Principiante', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acceso', models.CharField(help_text='Ej: Acceso total, Solo máquinas, Clases limitadas', max_length=100)),
                ('entrenador_personal_incluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('clases_impartidas', models.ManyToManyField(blank=True, related_name='instructores', to='app_gym.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('membresia_activa', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='miembros_imagenes/')),
                ('clase_inscrita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='app_gym.clase')),
                ('membresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='app_gym.membresia')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('calificacion_miembro', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calificación del miembro para esta clase (1-5)', null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clase', to='app_gym.clase')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clase', to='app_gym.miembro')),
            ],
            options={
                'verbose_name': 'Registro de Clase',
                'verbose_name_plural': 'Registros de Clases',
                'unique_together': {('miembro', 'clase', 'fecha_registro')},
            },
        ),
    ]
